checks:
  php:
    code_rating: true
    duplication: true
filter:
  excluded_paths:
    - tests/*
build:
  tests:
    override:
      -
        command: ./vendor/bin/phpunit --coverage-clover=clover.xml
        coverage:
          file: clover.xml
          format: php-clover
        services:
          # For available tags, see https://hub.docker.com/_/redis/
          redis: 4
